version: '3.8'

networks:
  xiaozhi-webui-net:
    driver: bridge

services:
  frontend:
    image: harbor.4pd.io/sagegpt-aio/xiaozhi/xiaozhi-webui:frontend-v250728-subpath
    environment:
      VITE_APP_BACKEND_URL: http://127.0.0.1/api/xiaozhi-webui-backend
    # ports:
    #   - 8380:80

    networks:
      - xiaozhi-webui-net

  backend:
    image: harbor.4pd.io/sagegpt-aio/xiaozhi/xiaozhi-webui:backend-v250728-subpath
    networks:
      - xiaozhi-webui-net
    # ports:
    #   - "8000:8000"
    #   - "5000:5000"
