version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      VITE_APP_BACKEND_URL: http://localhost/api/xiaozhi-webui-backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile