version: '3.8'

networks:
  xiaozhi-webui-net:
    driver: bridge

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      VITE_APP_BACKEND_URL: http://127.0.0.1/api/xiaozhi-webui-backend
    networks:
      - xiaozhi-webui-net

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    networks:
      - xiaozhi-webui-net
